config/routes.rb
DevotionApp::Application.routes.draw do

  get "upload/index"
  post "upload/uploadFile"
  get "upload/adhoc"
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :categories, only: [:show, :create, :destroy] do
    resources :devotionposts
  end
  resources :devotionposts
  
  root to: 'static_pages#home'
  
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/version', to: 'categories#version'
 

end

app/models/devotionpost.rb
class Devotionpost < ActiveRecord::Base
  belongs_to :category
  attr_accessible :address, :application, :bible_id, :content, :title, :intro, :title_en, :address_en, :content_en, :application_en, :intro_en
  
  validates :title, presence: true
  validates :address, presence: true
  validates :intro, :length => { :maximum => 200 }, presence: true
  validates :content, :length => { :maximum => 200 }, presence: true
  validates :application, :length => { :maximum => 200 }, presence: true
  validates :title_en, presence: true
  validates :address_en, presence: true
  validates :intro_en, :length => { :maximum => 200 }, presence: true
  validates :content_en, :length => { :maximum => 200 }, presence: true
  validates :application_en, :length => { :maximum => 200 }, presence: true
  
  default_scope order: 'devotionposts.created_at DESC'
end

app/controllers/devotionposts_controller.rb
class DevotionpostsController < ApplicationController
  before_filter :signed_in_user, only: [:edit, :create, :destroy]
  before_filter :correct_user,   only: :destroy
  
  def new
    @category_id = params[:id]
    @devotionpost = Devotionpost.new
  end
  
  def create
    @category_id = params[:devotionpost][:bible_id]
    @category = Category.find(@category_id)
    @devotionpost = @category.devotionposts.create(params[:devotionpost])
    # @devotionpost.bible_id = @category.bible_id
    
    @introlength = @devotionpost.intro.length
    @contentlength = @devotionpost.content.length
    @applicationlength = @devotionpost.application.length
    
    if @devotionpost.save
      # redirect_to root_path
      redirect_to @category, notice: 'Post was successfully created.'
    else
      render action: "new"
    end
  end
  
  def edit
    @devotionpost = Devotionpost.find(params[:id])
  end
  
  def update
    @devotionpost = Devotionpost.find(params[:id])
    @category = Category.find(@devotionpost.category_id)
    
    @introlength = @devotionpost.intro.length
    @contentlength = @devotionpost.content.length
    @applicationlength = @devotionpost.application.length

    respond_to do |format|
      if @devotionpost.update_attributes(params[:devotionpost])
        format.html { redirect_to @category, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @devotionpost.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @category = Category.find(params[:category_id])
    @devotionpost = @category.devotionposts.find(params[:id])
    @devotionpost.destroy
    redirect_to root_path
  end
end

app/helpers/devotionposts_helper.rb
module DevotionpostsHelper
end

app/views/devotionposts/_devotionpost.html.erb
<div class="center hero-unit">
	
  <p>
    <b>Title(제목):</b>
    <%= devotionpost.title %>
  </p>
 
  <p>
    <b>Address(주소):</b>
    <%= devotionpost.address %>
  </p>
  
  <p>
    <b>Intro(본문내용-개괄):</b>
    <%= devotionpost.intro %>
  </p>
  
  <p>
    <b>Content(의미):</b>
    <%= devotionpost.content %>
  </p>
  
  <p>
    <b>Application(적용):</b>
    <%= devotionpost.application %>
  </p>

  <% if signed_in? %>
  <p>
    <td><%= link_to 'Edit', edit_devotionpost_path(devotionpost) %></td>
  </p>

  <p>
    <%= link_to 'Destroy', [devotionpost.category, devotionpost],
                 :confirm => 'Are you sure?',
                 :method => :delete %>
  </p>
  <% else %>
  <% end %>
</div>

app/views/devotionposts/_form.html.erb
<%= form_for([@category, @category.devotionposts.build]) do |f| %>

  <%= render 'shared/error_messages', object: f.object %> 

  <div class="field">
    <%= f.label :title %>(제목)<br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :address %>(주소)<br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :intro %>(본문 설명-개괄)<br />
    <%= f.text_area :intro %>
  </div>
  <div class="field">
    <%= f.label :content %>(의미)<br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :application %>(적용)<br />
    <%= f.text_area :application %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/devotionposts/edit.html.erb
<h1>Editing devotion post</h1>

<%= form_for @devotionpost do |f| %>

  <%= render 'shared/error_messages', object: f.object %>

  <div class="field">
    <%= f.label :title %>(제목)<br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :address %>(주소)<br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :intro %>(본문 설명-개괄)
    <%= f.label :value => @introlength %>
    <%= f.text_area :intro %>
  </div>
  <div class="field">
    <%= f.label :content %>(의미)
    <%= f.label :value => @contentlength %>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :application %>(적용)
    <%= f.label :value => @applicationlength %>
    <%= f.text_area :application %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/devotionposts/new.html.erb
<h1>Add a devotion post:</h1>
 
<%= form_for(@devotionpost) do |f| %>

  <%= render 'shared/error_messages', object: f.object %> 

  <%= f.hidden_field :bible_id, :value => @category_id %>

  <div class="field">
    <%= f.label :title %>(제목)<br />
    <%= f.text_field :title, placeholder: "Korean" %>
    <%= f.text_field :title_en, placeholder: "English" %>
  </div>
  <div class="field">
    <%= f.label :address %>(주소)<br />
    <%= f.text_field :address, placeholder: "Korean" %>
    <%= f.text_field :address_en, placeholder: "English" %>
  </div>
  <div class="field">
    <%= f.label :intro %>(본문 설명-개괄)
    <%= f.label :value => @introlength %>
    <%= f.text_area :intro, placeholder: "Korean" %>
    <%= f.text_area :intro_en, placeholder: "English" %>
  </div>
  <div class="field">
    <%= f.label :content %>(의미)
    <%= f.label :value => @contentlength %>
    <%= f.text_area :content, placeholder: "Korean" %>
    <%= f.text_area :content_en, placeholder: "English" %>
  </div>
  <div class="field">
    <%= f.label :application %>(적용)
    <%= f.label :value => @applicationlength %>
    <%= f.text_area :application, placeholder: "Korean" %>
    <%= f.text_area :application_en, placeholder: "English" %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>